; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino

; Custom reset command
[platformio]
custom_commands = reset_mcu

; Reset MCU command - sends DTR signal to reset the Arduino
reset_mcu = platformio device monitor --port $UPLOAD_PORT --baud 1200 --send-command "reset"